// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp56czc9uKuo4_lS6kRoBlBAXWnl99MnQ',
    appId: '1:445914365318:web:fb613723d912c4b2bf4007',
    messagingSenderId: '445914365318',
    projectId: 'day16-b072f',
    authDomain: 'day16-b072f.firebaseapp.com',
    storageBucket: 'day16-b072f.firebasestorage.app',
    measurementId: 'G-79M0R0VN8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD29bAUVrqVLwxk2jIBFp220V_XSDjbMQA',
    appId: '1:445914365318:android:f052e72c16817220bf4007',
    messagingSenderId: '445914365318',
    projectId: 'day16-b072f',
    storageBucket: 'day16-b072f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzw0Y-5_kbm5iDiPfEIxFfVC2yxsiY6Sw',
    appId: '1:445914365318:ios:7aa3c23ff8916062bf4007',
    messagingSenderId: '445914365318',
    projectId: 'day16-b072f',
    storageBucket: 'day16-b072f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClass',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzw0Y-5_kbm5iDiPfEIxFfVC2yxsiY6Sw',
    appId: '1:445914365318:ios:7aa3c23ff8916062bf4007',
    messagingSenderId: '445914365318',
    projectId: 'day16-b072f',
    storageBucket: 'day16-b072f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY1NRpVp93BN62pgiV4MNLb1QXOjNzgSA',
    appId: '1:445914365318:web:cb86162752b7bb55bf4007',
    messagingSenderId: '445914365318',
    projectId: 'day16-b072f',
    authDomain: 'day16-b072f.firebaseapp.com',
    storageBucket: 'day16-b072f.firebasestorage.app',
    measurementId: 'G-CD4MDLP8J2',
  );
}
