// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHk0XRfrTHaOZHl461L4QWgwUQmXv1bG8',
    appId: '1:129667039338:web:5412142ff191b547f68a13',
    messagingSenderId: '129667039338',
    projectId: 'fir-class-14737',
    authDomain: 'fir-class-14737.firebaseapp.com',
    storageBucket: 'fir-class-14737.firebasestorage.app',
    measurementId: 'G-1NMMMGVPSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN5sixTlYrB88eJ4r2C2b7pxnZDVblAaM',
    appId: '1:129667039338:android:55e67df284c51621f68a13',
    messagingSenderId: '129667039338',
    projectId: 'fir-class-14737',
    storageBucket: 'fir-class-14737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1d7_AKsyrZMCuP3WUv8BMHGv9WFRxzEM',
    appId: '1:129667039338:ios:24021d73f340b5c7f68a13',
    messagingSenderId: '129667039338',
    projectId: 'fir-class-14737',
    storageBucket: 'fir-class-14737.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1d7_AKsyrZMCuP3WUv8BMHGv9WFRxzEM',
    appId: '1:129667039338:ios:24021d73f340b5c7f68a13',
    messagingSenderId: '129667039338',
    projectId: 'fir-class-14737',
    storageBucket: 'fir-class-14737.firebasestorage.app',
    iosBundleId: 'com.example.firebaseClass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHk0XRfrTHaOZHl461L4QWgwUQmXv1bG8',
    appId: '1:129667039338:web:6c60e40d084003ebf68a13',
    messagingSenderId: '129667039338',
    projectId: 'fir-class-14737',
    authDomain: 'fir-class-14737.firebaseapp.com',
    storageBucket: 'fir-class-14737.firebasestorage.app',
    measurementId: 'G-XK3QQHNLHB',
  );
}
